# Funding options for Academic Draft AI

github: []  # Add your GitHub Sponsors username here when ready
patreon: ""
open_collective: ""
ko_fi: ""
custom: []

# This project is open source and free to use.
# Consider supporting by:
# - Starring the repository
# - Contributing code or documentation
# - Sharing with colleagues
